Repository SSA-FY/backend, pull requests merged in 2024-06, with the labels that each got.

#48 DataResponse 생성, Swagger custom annotation 생성
  src/main/java/ssafy/lambda/global/annotation/ApiErrorResponse.java
  src/main/java/ssafy/lambda/global/config/SwaggerConfig.java
  src/main/java/ssafy/lambda/global/exception/GlobalExceptionHandler.java
  src/main/java/ssafy/lambda/global/response/ApiError.java
  src/main/java/ssafy/lambda/global/response/Response.java
  src/main/java/ssafy/lambda/global/response/dto/Response.java
  src/main/java/ssafy/lambda/global/response/dto/ResponseData.java
  src/main/java/ssafy/lambda/invitation/controller/InvitationController.java
  src/main/java/ssafy/lambda/member/controller/MemberController.java
  src/main/java/ssafy/lambda/team/controller/TeamController.java
Labels: ✨ feature

#50 Vote, ExpiredVote isProceeding 필드 삭제
  src/main/java/ssafy/lambda/board/entity/ExpiredVote.java
  src/main/java/ssafy/lambda/vote/entity/Vote.java
  src/main/java/ssafy/lambda/vote/repository/VoteRepositoryImpl.java
  src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
Labels: ✨ feature

#54 Notification 기능 개발
  src/main/java/ssafy/lambda/board/repository/ExpiredVoteRepository.java
  src/main/java/ssafy/lambda/global/exception/GlobalExceptionHandler.java
  src/main/java/ssafy/lambda/global/exception/UnauthorizedMemberException.java
  src/main/java/ssafy/lambda/global/response/ApiError.java
  src/main/java/ssafy/lambda/notification/controller/NotificationController.java
  src/main/java/ssafy/lambda/notification/dto/ResponseExpiredVoteNotification.java
  src/main/java/ssafy/lambda/notification/dto/ResponseInvitionNotification.java
  src/main/java/ssafy/lambda/notification/dto/ResponseNotificationDto.java
  src/main/java/ssafy/lambda/notification/dto/ResponseVoteNotification.java
  src/main/java/ssafy/lambda/notification/dto/item/VoteInfoItem.java
  src/main/java/ssafy/lambda/notification/entity/Notification.java
  src/main/java/ssafy/lambda/notification/entity/NotificationDetail/ExpiredVoteNotification.java
  src/main/java/ssafy/lambda/notification/entity/NotificationDetail/InvitationNotification.java
  src/main/java/ssafy/lambda/notification/entity/NotificationDetail/VoteNotification.java
  src/main/java/ssafy/lambda/notification/exception/NotificationNotFoundException.java
  src/main/java/ssafy/lambda/notification/repository/CustomNotificationRepository.java
  src/main/java/ssafy/lambda/notification/repository/NotificationRepository.java
  src/main/java/ssafy/lambda/notification/repository/NotificationRepositoryImpl.java
  src/main/java/ssafy/lambda/notification/service/NotificationService.java
  src/main/java/ssafy/lambda/notification/service/NotificationServiceImpl.java
Labels: ✨ feature

#61 Vote 도메인 리팩토링 및 기능 추가
  src/main/java/ssafy/lambda/vote/controller/VoteController.java
  src/main/java/ssafy/lambda/vote/repository/VoteRepositoryImpl.java
  src/main/java/ssafy/lambda/vote/service/VoteService.java
  src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
Labels: ✨ feature, ♻️ refactor

#66 Team 도메인 기능 추가 및 수정
  src/main/java/ssafy/lambda/global/exception/GlobalExceptionHandler.java
  src/main/java/ssafy/lambda/global/response/ApiError.java
  src/main/java/ssafy/lambda/member/dto/ResponseMemberDto.java
  src/main/java/ssafy/lambda/member/repository/MemberRepository.java
  src/main/java/ssafy/lambda/member/service/MemberService.java
  src/main/java/ssafy/lambda/member/service/MemberServiceImpl.java
  src/main/java/ssafy/lambda/membership/dto/RequestChangeNicknameDto.java
  src/main/java/ssafy/lambda/membership/dto/ResponseMembershipDto.java
  src/main/java/ssafy/lambda/membership/repository/MembershipRepository.java
  src/main/java/ssafy/lambda/team/controller/TeamController.java
  src/main/java/ssafy/lambda/team/dto/RequestTeamCreateDto.java
  src/main/java/ssafy/lambda/team/dto/RequestTeamManagerChangeDto.java
  src/main/java/ssafy/lambda/team/dto/RequestTeamNameUpdateDto.java
  src/main/java/ssafy/lambda/team/dto/RequestTeamUpdateDto.java
  src/main/java/ssafy/lambda/team/dto/ResponseTeamDto.java
  src/main/java/ssafy/lambda/team/entity/Team.java
  src/main/java/ssafy/lambda/team/exception/DuplicatedTeamNameException.java
  src/main/java/ssafy/lambda/team/exception/ExitTeamException.java
  src/main/java/ssafy/lambda/team/repository/TeamRepository.java
  src/main/java/ssafy/lambda/team/service/TeamService.java
  src/main/java/ssafy/lambda/team/service/TeamServiceImpl.java
Labels: ⚙️ chore, ✨ feature, 🔨 fix, ♻️ refactor

#67 feat: invitation 초대 생성 배열로 변경
  src/main/java/ssafy/lambda/invitation/controller/InvitationController.java
Labels: ⚙️ chore

#65 Point 도메인 및 기능 개발
  src/main/java/ssafy/lambda/accesstoken/dto/ResponseAccessTokenDto.java
  src/main/java/ssafy/lambda/accesstoken/service/AccessTokenService.java
  src/main/java/ssafy/lambda/global/security/oauth2/OAuth2MemberCustomService.java
  src/main/java/ssafy/lambda/member/entity/Member.java
  src/main/java/ssafy/lambda/member/service/MemberService.java
  src/main/java/ssafy/lambda/member/service/MemberServiceImpl.java
  src/main/java/ssafy/lambda/point/controller/PointController.java
  src/main/java/ssafy/lambda/point/dto/ResponseGetPointDto.java
  src/main/java/ssafy/lambda/point/entity/Point.java
  src/main/java/ssafy/lambda/point/repository/PointRepository.java
  src/main/java/ssafy/lambda/point/service/PointService.java
  src/main/java/ssafy/lambda/team/controller/TeamController.java
  src/main/java/ssafy/lambda/team/dto/ResponseTeamGetDto.java
Labels: ✨ feature

#69 투표 생성 시 이미지 추가 및 팀 반환 로직 개발
  src/main/java/ssafy/lambda/LambdaApplication.java
  src/main/java/ssafy/lambda/team/dto/ResponseTeamVoteWhetherDto.java
  src/main/java/ssafy/lambda/team/service/TeamWithVoteService.java
  src/main/java/ssafy/lambda/team/service/TeamWithVoteServiceImpl.java
  src/main/java/ssafy/lambda/vote/controller/VoteController.java
  src/main/java/ssafy/lambda/vote/dto/RequestReviewDto.java
  src/main/java/ssafy/lambda/vote/dto/RequestVoteDto.java
  src/main/java/ssafy/lambda/vote/repository/VoteRepositoryCustom.java
  src/main/java/ssafy/lambda/vote/repository/VoteRepositoryImpl.java
  src/main/java/ssafy/lambda/vote/service/VoteService.java
  src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
Labels: ✨ feature

#70 Board 도메인 수정 및 개발
  src/main/java/ssafy/lambda/board/controller/BoardController.java
  src/main/java/ssafy/lambda/board/dto/MemberWithPercenCntDto.java
  src/main/java/ssafy/lambda/board/dto/ResponseBoardDetailDto.java
  src/main/java/ssafy/lambda/board/dto/ResponseBoardSummaryDto.java
  src/main/java/ssafy/lambda/board/dto/ResponseCommentDto.java
  src/main/java/ssafy/lambda/board/entity/BoardComment.java
  src/main/java/ssafy/lambda/board/repository/BoardRepositoryCustom.java
  src/main/java/ssafy/lambda/board/repository/CommentRepository.java
  src/main/java/ssafy/lambda/board/repository/ExpiredVoteRepository.java
  src/main/java/ssafy/lambda/board/repository/ExpiredVoteRepositoryImpl.java
  src/main/java/ssafy/lambda/board/service/BoardService.java
  src/main/java/ssafy/lambda/board/service/BoardServiceImpl.java
  src/main/java/ssafy/lambda/global/response/ApiError.java
Labels: ✨ feature

#75 fix: @Param 추가
  src/main/java/ssafy/lambda/membership/repository/MembershipRepository.java
Labels: ✨ feature

#76 fix: member 찾기 이메일 -> 태그 변경
  src/main/java/ssafy/lambda/member/controller/MemberController.java
Labels: 🔨 fix

#77 feat: invitation 초대시 알림 생성
  src/main/java/ssafy/lambda/invitation/service/InvitationServiceImpl.java
Labels: ✨ feature

#78 fix: team 관련 api 수정
  src/main/java/ssafy/lambda/LambdaApplication.java
  src/main/java/ssafy/lambda/board/entity/BoardComment.java
  src/main/java/ssafy/lambda/invitation/controller/InvitationController.java
  src/main/java/ssafy/lambda/invitation/service/InvitationServiceImpl.java
  src/main/java/ssafy/lambda/member/controller/MemberController.java
  src/main/java/ssafy/lambda/team/controller/TeamController.java
  src/main/java/ssafy/lambda/team/dto/RequestTeamCreateDto.java
  src/main/java/ssafy/lambda/team/dto/RequestTeamUpdateDto.java
  src/main/java/ssafy/lambda/team/dto/ResponseTeamDto.java
  src/main/java/ssafy/lambda/team/entity/Team.java
  src/main/java/ssafy/lambda/team/service/TeamService.java
  src/main/java/ssafy/lambda/team/service/TeamServiceImpl.java
Labels: 🔨 fix, ♻️ refactor

#80 fix: 그룹 생성시 imgUrl 에러
  src/main/java/ssafy/lambda/team/service/TeamServiceImpl.java
Labels: 🔨 fix
